### ISSUE TITLE
resolution changes without changing slept and delta values

### ISSUE THREAD

**Issue by theSilver32** [amitxv/TimerResolution#10]
the problem is that i did create the d-word value in the registry and i can change resolution, but without changing any sleep and delta value (see screenshot) i even tried to  | bcedit /set useplatformtick yes |   | bcedit /set disabledynamictick yes |   | bcedit /deletevalue useplatformclock |   but still doesn't work properly. IM ON WINDOWS 10 BUILD 19045

![Screenshot (3)](https://github.com/amitxv/TimerResolution/assets/102018053/e0a869f0-5b28-4035-8350-66b9c599cb3b)

**Comment by amitxv** [comment]
The registry key does not exist on your OS. See https://github.com/amitxv/PC-Tuning/blob/main/docs/research.md#fixing-timing-precision-in-windows-after-the-great-rule-change
