### ISSUE TITLE
slept does not change after completing the steps!

### ISSUE THREAD

**Issue by mrxt0098** [amitxv/TimerResolution#16]
Hello
I did all the steps correctly, but in the end, the slept value still does not fall below 15! How do I fix it?

![image](https://github.com/amitxv/TimerResolution/assets/135238006/60028fb4-e40c-43ac-8e14-d6a3b181001d)

![image](https://github.com/amitxv/TimerResolution/assets/135238006/eb154b2e-0149-4954-98e3-adc2284a5504)

**Comment by amitxv** [comment]
This OS version does not support global timer resolution.

**Comment by mrxt0098** [comment]
> This OS version does not support global timer resolution.

Thank you for your reply! I wanted to know if I want to use it, should I downgrade or install a newer version? And is there a visible difference in the input lag, so is it worth changing my windows for it?
