### ISSUE TITLE
setprocess information

### ISSUE THREAD

**Issue by btsambo** [amitxv/TimerResolution#17]
Hi Sorry to bother - it's more of a query so apologies in advance

if setting up timer resolution and fine tuning do we also need to do the setprocess information part?

or is adding the global reg entry enough

thanks in advance!

:)

**Comment by amitxv** [comment]
SetProcessInformation is called in the program:

https://github.com/amitxv/TimerResolution/blob/e84f83e03ed1741c7cddccff219ce69d1fceae25/SetTimerResolution/SetTimerResolution/SetTimerResolution.cpp#L91

**Comment by btsambo** [comment]
Sorry ignore my last got confused by the .cpp thing
