### ISSUE TITLE
Sleep spikes

### ISSUE THREAD

**Issue by spin240** [amitxv/TimerResolution#18]
Hello,

As far as I understand I did everything according to the instructions, however while doing a test in MeasureSleep program I can see some sleep spikes. I pinned a screenshot to my message. Do you have any ideas what could be causing this issue?
![image](https://github.com/amitxv/TimerResolution/assets/1363086/2f896b2c-e0df-49de-9c2c-a918fab1e456)

**Comment by amitxv** [comment]
Raise the resolution further and monitor STDEV in a similar fasion to: https://github.com/amitxv/TimerResolution#lower-resolution-yet-higher-precision.
