### ISSUE TITLE
SetTimerResolution.exe Flashes and Closes

### ISSUE THREAD

**Issue by CryptoKline** [amitxv/TimerResolution#19]
After downloading, i moved both MeasureSleep and SetTimerResolution to the root of C: Drive. MeasureSleep opens and works fine but when I try to open SetTimerResolution, it flashes a black window that almost looks like a command prompt window but it closes so fast you can't tell what it is. Its almost like a blank cmd prompt window is trying to open but is terminated immediately. but this happens in the snap of a finger. 

Also, I searched through the Readme file and couldn't find what I should be setting the values to for useplatformclock, useplatformtick, disabledynamictick, and tscsyncpolicy. I read the great rule change article as well to see if it was in there. Maybe I'm missing something but I couldn't find the info anywhere.

**Comment by CryptoKline** [comment]
That was my mistake, I thought there was a GUI that was supposed to launch. It's running in the background and is working correctly. I just don't know what the suggested settings for those 4 bcdedits are. Also the auto benchmark automation ps1 thing has no instructions. I can't figure it out

**Comment by amitxv** [comment]
https://github.com/amitxv/PC-Tuning/blob/main/docs/post-install.md#configure-the-bcd-store

https://github.com/amitxv/PC-Tuning/blob/main/docs/post-install.md#raise-the-clock-interrupt-frequency-timer-resolution
