### ISSUE TITLE
Tray icon for timer resolution & '-hidden' argument

### ISSUE THREAD

**Issue by he3als** [amitxv/TimerResolution#2]
Could be useful for testing/general ease of use to have a tray icon where you can:
- Exit the program
- Apply the GlobalTimerResolutionRequests tweak
- Set a custom timer resolution (1ms, 0.5ms, etc)
- Launch on startup

It would also be good to have a `-hidden` argument for users that do not want it in tray constantly.

**Comment by amitxv** [comment]
> Exit the program
Apply the GlobalTimerResolutionRequests tweak

These sound appealing but my main goal was to create a minimal, hidden program and not a utility.

> Set a custom timer resolution (1ms, 0.5ms, etc)
Launch on startup

I'm currently in the process of implementing CLI arguments for desired resolution/hidden console and updating the docs for instructions on starting the program automatically.

**Comment by amitxv** [comment]
``--resolution`` and ``--no-console`` added in https://github.com/amitxv/TimerResolution/commit/ca4a0724488eecefab459afb6b687b2a404b2c80.

**Comment by techgamers2** [comment]
still when i startup cmd windows comes and closes can tht process happen minimized or if possible ability to install timerresolution.exe as a service like [hone ctrl](https://github.com/auraside/HoneCtrl) offers

**Comment by amitxv** [comment]
Absolutely no plans to convert to a service. The tools are meant to compliment my research which involve killing/launching them several times which is not practical with a service.

- See [Micro-adjusting timer resolution for higher precision](https://github.com/amitxv/PC-Tuning/blob/main/docs/research.md#micro-adjusting-timer-resolution-for-higher-precision)

Alternatively, you can compile the tools as console-less programs manually to prevent a CMD window from appearing at startup.

**Comment by techgamers2** [comment]
can u add an argument like --minimized ? coz everytime i boot its comes up ...its not problem just doesnt seems normal.... if its not possible i completely understand

**Comment by amitxv** [comment]
Maybe in the future I will modify how ``--no-console`` works. As mentioned, for now you can compile it as a console-less application.
