### ISSUE TITLE
Timer Resolution can't run in background and doesn't work.

### ISSUE THREAD

**Issue by SwiftyPop** [amitxv/TimerResolution#21]
UPDATE: So, I moved the shortcut to shell:startup and restart my PC. At first boot, it doesn't seem to work but after a while, it's working now. I guess it fixed now? I will check if it's permanently fixed or not
![image](https://github.com/amitxv/TimerResolution/assets/90952326/aebdbd88-4686-4c3f-a4b4-7843f53ab1b0)

So, my app keeps crashing when I try to open the exe. Initially, everything was smooth sailing—I could tweak resolution values with shortcuts and keep it running in the background. But now, no luck. I've tried restarting my PC, re-downloading TimerResolution, and even moved its directory directly to C, but nada. This all started after running the [micro-adjust-benchmark.ps1](https://github.com/amitxv/TimerResolution/blob/main/micro-adjust-benchmark.ps1) script. Wondering if that benchmark did something funky to my PC. Any ideas?

I am on Windows 11 22H2 and did make that registry changes too. I mean it works before why not now?

**Comment by btsambo** [comment]
hi don't know if this helps but i have noticed something - if you run the benchmark the timer gets reset to 15ms and a reboot is necessary to reinvoke the timer res set in the shell:startup shortcut

other than that it works amazing for me

**Comment by SwiftyPop** [comment]
@btsambo @amitxv  Thanks, seems like putting the TimerResolution.exe shortcut in the shell:startup and restarting my PC permanently fixed the issue.
