### ISSUE TITLE
Have high Slept1 and Delta values.

### ISSUE THREAD

**Issue by angelooo18** [amitxv/TimerResolution#4]
Win10 22H2 19045.2787
I have set the a .bat with the commands of execute (at 1ms) in Task Scheduler with High privileges and after reboot im getting the cmd window open with the command and my measure sleep looks like this:

Resolution: 0.999400000000ms, Sleep(1) slept 3.520000000000ms (delta: 2.520000000000) (HERE I OPEN THE PROGAM)
Resolution: 0.999400000000ms, Sleep(1) slept 15.987400000000ms (delta: 14.987400000000)
Resolution: 0.999400000000ms, Sleep(1) slept 15.987400000000ms (delta: 14.987400000000)
Resolution: 0.999400000000ms, Sleep(1) slept 15.988100000000ms (delta: 14.988100000000)
Resolution: 0.999400000000ms, Sleep(1) slept 15.989600000000ms (delta: 14.989600000000)
Resolution: 0.999400000000ms, Sleep(1) slept 15.986000000000ms (delta: 14.986000000000)
Resolution: 0.999400000000ms, Sleep(1) slept 15.993400000000ms (delta: 14.993400000000)
Resolution: 0.999400000000ms, Sleep(1) slept 15.987300000000ms (delta: 14.987300000000)
Resolution: 0.999400000000ms, Sleep(1) slept 15.988600000000ms (delta: 14.988600000000)

Tell me please if I have to bring more info

**Comment by amitxv** [comment]
You can't officially restore the old/global timer resolution implementation on 22H2. Please read [Raise the Clock Interrupt Frequency (Timer Resolution)](https://github.com/amitxv/PC-Tuning/blob/main/docs/post-install.md#raise-the-clock-interrupt-frequency-timer-resolution) for more info.
