### ISSUE TITLE
Resolution wont change

### ISSUE THREAD

**Issue by ricardofelixb** [amitxv/TimerResolution#6]
After applying the reg edit and adding the shortcut with the right target and location, my resolution wont change, it remains at 0.5ms when I'm trying to adjust to 0.504.

Any idea why? Thanks :)

**Comment by amitxv** [comment]
You have another process calling for a higher resolution. You can use powercfg or Windows Performance Analyzer to check what process this is.

**Comment by ricardofelixb** [comment]
Could you guide me on how to do that with powercfg?

Here's bcdedit /enum if it helps, thanks :)

Windows Boot Manager
--------------------
identifier              {bootmgr}
device                  partition=\Device\HarddiskVolume4
path                    \EFI\Microsoft\Boot\bootmgfw.efi
description             Windows Boot Manager
locale                  en-US
inherit                 {globalsettings}
default                 {current}
resumeobject            {92ba8b60-74a9-11ee-8600-8c882b251c28}
displayorder            {current}
toolsdisplayorder       {memdiag}
timeout                 30

Windows Boot Loader
-------------------
identifier              {current}
device                  partition=C:
path                    \WINDOWS\system32\winload.efi
description             Windows 11
locale                  en-US
inherit                 {bootloadersettings}
recoverysequence        {92ba8b63-74a9-11ee-8600-8c882b251c28}
displaymessageoverride  Recovery
recoveryenabled         Yes
isolatedcontext         Yes
allowedinmemorysettings 0x15000075
osdevice                partition=C:
systemroot              \WINDOWS
resumeobject            {92ba8b60-74a9-11ee-8600-8c882b251c28}
nx                      OptIn
bootmenupolicy          Standard
useplatformtick         No

**Comment by amitxv** [comment]
Look into ``powercfg -energy``.

**Comment by ricardofelixb** [comment]
Thanks, so I found out its my audio interface driver. Any idea on how to restrict it from changin my resolution?

**Comment by ricardofelixb** [comment]
Also, when I play a game, it switches to 0.5, and whe I close the game, the micro adjusted resolution gets re applied. Any idea on how to restrict processes or drivers on changing the resolution?

Thanks!

**Comment by amitxv** [comment]
You can't. If another process is calling for a higher resolution, then your's will be overridden.
