### ISSUE TITLE
Prevent other software from further lowering Timer Resolution?

### ISSUE THREAD

**Issue by Immune2AIDS** [amitxv/TimerResolution#8]
For example: 

I use this repo's settimerresolution.exe at 0.507ms to get the best precision (closest to 1ms Sleep Measure for me) but another program like emulators like Yuzu.exe or games like Ghostrunner 2 call NtSetTimerResolution on windows to lower it down further to 0.500ms.

Is there any way to prevent that or will it always be lowest request? Like possibly via an exception or process priority?

Sorry if it's hard to understand what I mean, I can try to explain further if needed.

**Comment by amitxv** [comment]
Not that I am aware of, you can either compile the application yourself and modify the code that raises the resolution or experiment with DLL injection for non-anticheat games if re-compiling isn't an option.
